/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import servicios.MS_SQLServer;
import servicios.ValidacionDatos;

/**
 *
 * @author lnarvaezb
 */
public class Conf_Server extends javax.swing.JInternalFrame {

    /**
     * Creates new form Conf_Server
     */
    public Conf_Server() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtServerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtDateBase = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtPort = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPswPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jCmbTypeServer = new javax.swing.JComboBox<>();
        jBtn__Guardar = new javax.swing.JButton();
        jBtnTestCnx = new javax.swing.JButton();
        jBrnHelp = new javax.swing.JButton();
        jBtn_closed = new javax.swing.JButton();
        jTxtUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setTitle("Configuración Acceso a Datos");

        jLabel1.setText("Nombre del Servidor");

        jTxtServerName.setToolTipText("Indicar el nombre de servidor");
        jTxtServerName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtServerNameMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Configurar Servidor");

        jLabel3.setText("Base de Datos");

        jTxtDateBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtDateBaseMouseClicked(evt);
            }
        });

        jLabel4.setText("Puerto");

        jTxtPort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtPortMouseClicked(evt);
            }
        });

        jLabel5.setText("Usuario");

        jPswPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPswPasswordMouseClicked(evt);
            }
        });

        jLabel6.setText("Tipo Servidor");

        jCmbTypeServer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "MS-SQL Server", "MySQL", "PostgreSQL" }));

        jBtn__Guardar.setText("Guardar");
        jBtn__Guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtn__Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn__GuardarActionPerformed(evt);
            }
        });

        jBtnTestCnx.setText("Probar Conexión");
        jBtnTestCnx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnTestCnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTestCnxActionPerformed(evt);
            }
        });

        jBrnHelp.setText("Ayuda");
        jBrnHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jBtn_closed.setText("Cerrar");
        jBtn_closed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtn_closed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_closedActionPerformed(evt);
            }
        });

        jTxtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtUserMouseClicked(evt);
            }
        });

        jLabel7.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtServerName)
                            .addComponent(jTxtDateBase)
                            .addComponent(jTxtPort)
                            .addComponent(jPswPassword)
                            .addComponent(jCmbTypeServer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jBtn__Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnTestCnx)
                        .addGap(16, 16, 16)
                        .addComponent(jBrnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtn_closed, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtServerName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDateBase, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbTypeServer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPswPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn__Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnTestCnx, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_closed, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_closedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_closedActionPerformed
        // TODO add your handling code here:
        this.dispose(); //Cerrar la ventana
    }//GEN-LAST:event_jBtn_closedActionPerformed
    /**
     * Busca establecer la conexión con el servidor de bases de datos indicado 
     * los datos de configuración
     * @param evt manejador para determinar el evento
     */
    private void jBtn__GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn__GuardarActionPerformed
        
    }//GEN-LAST:event_jBtn__GuardarActionPerformed
    
    private void jTxtServerNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtServerNameMouseClicked
        // TODO add your handling code here:        
        this.jTxtServerName.setBackground(Color.WHITE);        
    }//GEN-LAST:event_jTxtServerNameMouseClicked

    private void jBtnTestCnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTestCnxActionPerformed
        // TODO add your handling code here:
        try {            
             if (ValidacionCampos ()){
                MS_SQLServer con = new MS_SQLServer ();
                JOptionPane.showMessageDialog(rootPane, "Estamos Bien, un exito"); 
             }//Fin de la instrucción if
             else {
                 JOptionPane.showMessageDialog(this, "Existen campos que no han"
                                      + " sido completados o estan incorrectos", 
                                "Error en Captura de Datos", JOptionPane.ERROR_MESSAGE);
             }//Fin else
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Clase no encontrada:" 
                        + ex.getMessage() + "\n", "Error de Librería"
                        , JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error de instancia: " 
                        + ex.getMessage() + "\n", "Error de Librería"
                        , JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
                JOptionPane.showMessageDialog(rootPane, "Acceso Ilegal: " 
                        + ex.getMessage() + "\n", "Error de Acceso"
                        , JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Acceso Ilegal: " 
                        + ex.getMessage() + "\n", "Error SQLException"
                        , JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnTestCnxActionPerformed

    private void jTxtDateBaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtDateBaseMouseClicked
        // TODO add your handling code here:
        this.jTxtDateBase.setBackground(Color.WHITE); 
    }//GEN-LAST:event_jTxtDateBaseMouseClicked

    private void jTxtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtUserMouseClicked
        // TODO add your handling code here:
        this.jTxtUser.setBackground(Color.WHITE); 
    }//GEN-LAST:event_jTxtUserMouseClicked

    private void jPswPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPswPasswordMouseClicked
        // TODO add your handling code here:
        this.jPswPassword.setBackground(Color.WHITE); 
    }//GEN-LAST:event_jPswPasswordMouseClicked

    private void jTxtPortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtPortMouseClicked
        // TODO add your handling code here:
        this.jTxtPort.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTxtPortMouseClicked
    
    private boolean ValidacionCampos () {
        boolean valido =true;        
        if (!ValidacionDatos.isTextFieldValid(jTxtServerName, 
                                             jTxtServerName.getText(),8, 128))
            valido = false;
        //Validar en el campo nombre de base de datos
        if (!ValidacionDatos.isTextFieldValid(jTxtDateBase, 
                                             jTxtDateBase.getText(),6, 64))
            valido = false;
        //Validar en el campo número de puerto para conexion
        if (!ValidacionDatos.isNumValido(jTxtPort))
            valido = false;
        //Validar en el campo nombre de usuario para la conexión
        if (!ValidacionDatos.isTextFieldValid(jTxtUser,
                                             jTxtUser.getText(), 4, 64))
            valido = false;
        //Validar en el campo clave de usuario que tenga datos
        if (this.jPswPassword.getPassword().length < 6 || 
            this.jPswPassword.getPassword().length > 24)
        {
            this.jPswPassword.setBackground(Color.red);
            return false;
        }
        //Regresar verdadero si se han superado las validaciones
        return valido;
    }//Fin de validación
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBrnHelp;
    private javax.swing.JButton jBtnTestCnx;
    private javax.swing.JButton jBtn__Guardar;
    private javax.swing.JButton jBtn_closed;
    private javax.swing.JComboBox<String> jCmbTypeServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPswPassword;
    private javax.swing.JTextField jTxtDateBase;
    private javax.swing.JTextField jTxtPort;
    private javax.swing.JTextField jTxtServerName;
    private javax.swing.JTextField jTxtUser;
    // End of variables declaration//GEN-END:variables
}
