/*
 * Proyecto: Sistema para el control de Registro y Solicitudes de Titulos
 * Descripción: Clase por medio de la cual interactua el usuario con el sistema
 *              para el manejo de entrada de instancias Personal Operativo
 * Fecha: 18/05/2023
 */
package ui;

import controlador.CtrlOperativo;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import negocio.PersonalOperativo;
import ui.listados.Jif_ListaPersonalOperativo;

/**
 *
 * @author Lawdee Norman Narváez B.
 * @version 1.0.0
 * @since JDK 17.0.5
 * @see controlador.CtrlOperativo
 * 
 */
public class FrmPersonalOperativo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmPersonalTecnico
     */
    public FrmPersonalOperativo() {
        initComponents();
        //Establecer el color del fondo para la ventana
        this.getContentPane().setBackground(new Color (130, 170, 227));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitulo = new javax.swing.JLabel();
        jLbl_Image = new javax.swing.JLabel();
        jLbl_INSS = new javax.swing.JLabel();
        jTxtInss = new javax.swing.JTextField();
        jLblNombres = new javax.swing.JLabel();
        jTxtNombres = new javax.swing.JTextField();
        jLblApellido1 = new javax.swing.JLabel();
        jTxtPApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPnlNav = new javax.swing.JPanel();
        jTbtnGrabar = new javax.swing.JToggleButton();
        jTbtnBuscar = new javax.swing.JToggleButton();
        jTbtnBaja = new javax.swing.JToggleButton();
        jTbtnListar = new javax.swing.JToggleButton();
        jTxtSApellido = new javax.swing.JTextField();
        jLblCorreo = new javax.swing.JLabel();
        jTxtCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCmbFuncion = new javax.swing.JComboBox<>();

        setBorder(null);
        setClosable(true);
        setTitle("Personal Asistente");
        setFrameIcon(null);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(522, 388));
        setPreferredSize(new java.awt.Dimension(522, 400));

        jLblTitulo.setBackground(new java.awt.Color(255, 102, 153));
        jLblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblTitulo.setText("Personal Operativo");

        jLbl_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/personal1.png"))); // NOI18N
        jLbl_Image.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jLbl_Image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLbl_INSS.setText("INSS");

        jLblNombres.setText("Nombres");

        jLblApellido1.setText("Primer Apellido");

        jLabel6.setText("Segundo Apellido");

        jPnlNav.setBackground(new java.awt.Color(145, 216, 228));
        jPnlNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jTbtnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/guardar_24.gif"))); // NOI18N
        jTbtnGrabar.setMnemonic('g');
        jTbtnGrabar.setText("Grabar");
        jTbtnGrabar.setToolTipText("Grabar Información");
        jTbtnGrabar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTbtnGrabar.setBorderPainted(false);
        jTbtnGrabar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTbtnGrabar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jTbtnGrabar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jTbtnGrabar.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTbtnGrabar.setMaximumSize(new java.awt.Dimension(82, 30));
        jTbtnGrabar.setMinimumSize(new java.awt.Dimension(80, 26));
        jTbtnGrabar.setPreferredSize(new java.awt.Dimension(70, 32));
        jTbtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbtnGrabarActionPerformed(evt);
            }
        });

        jTbtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buscar_24.gif"))); // NOI18N
        jTbtnBuscar.setMnemonic('b');
        jTbtnBuscar.setText("Buscar");
        jTbtnBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTbtnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTbtnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jTbtnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jTbtnBuscar.setIconTextGap(8);
        jTbtnBuscar.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTbtnBuscar.setMaximumSize(new java.awt.Dimension(82, 30));
        jTbtnBuscar.setPreferredSize(new java.awt.Dimension(70, 32));
        jTbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbtnBuscarActionPerformed(evt);
            }
        });

        jTbtnBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/elimina_24.png"))); // NOI18N
        jTbtnBaja.setText("Baja");
        jTbtnBaja.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTbtnBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTbtnBaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jTbtnBaja.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jTbtnBaja.setIconTextGap(8);
        jTbtnBaja.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTbtnBaja.setMaximumSize(new java.awt.Dimension(82, 30));
        jTbtnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbtnBajaActionPerformed(evt);
            }
        });

        jTbtnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/instruct_24.jpg"))); // NOI18N
        jTbtnListar.setMnemonic('l');
        jTbtnListar.setText("Listar");
        jTbtnListar.setToolTipText("Listar Personal");
        jTbtnListar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTbtnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTbtnListar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jTbtnListar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jTbtnListar.setIconTextGap(8);
        jTbtnListar.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTbtnListar.setMaximumSize(new java.awt.Dimension(82, 30));
        jTbtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbtnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlNavLayout = new javax.swing.GroupLayout(jPnlNav);
        jPnlNav.setLayout(jPnlNavLayout);
        jPnlNavLayout.setHorizontalGroup(
            jPnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTbtnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTbtnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTbtnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlNavLayout.setVerticalGroup(
            jPnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlNavLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTbtnListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTbtnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTbtnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLblCorreo.setText("Correo");

        jLabel1.setText("Función");

        jCmbFuncion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "RESPONSABLE", "OPERADOR" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLbl_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCorreo)
                            .addComponent(jLabel1)
                            .addComponent(jLblApellido1)
                            .addComponent(jLblNombres)
                            .addComponent(jLbl_INSS))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtCorreo)
                    .addComponent(jTxtInss)
                    .addComponent(jTxtPApellido)
                    .addComponent(jTxtNombres)
                    .addComponent(jTxtSApellido)
                    .addComponent(jCmbFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnlNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblTitulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtInss, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_INSS))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblNombres, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtPApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblApellido1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLbl_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtSApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCorreo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCmbFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30))
        );

        setBounds(0, 0, 536, 388);
    }// </editor-fold>//GEN-END:initComponents

    private void jTbtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbtnGrabarActionPerformed
        
        try {
            // Preparar los datos que se guardaran del tecnico:
            int rst = CtrlOperativo.agregar(
                                    Integer.parseInt(this.jTxtInss.getText()), 
                                    this.jTxtNombres.getText().toUpperCase(),
                                    this.jTxtPApellido.getText().toUpperCase(),
                                    this.jTxtSApellido.getText().toUpperCase(),
                                    this.jTxtCorreo.getText(),
                                    this.jCmbFuncion.getSelectedItem().toString()
                                    );                                            
            if (rst > 0) {
                JOptionPane.showMessageDialog(this, "Registro grabado con exito"
                        , "Grabar Registro", JOptionPane.INFORMATION_MESSAGE);
                this.clearForm(); //Limpiar los campos del formulario
            }//Fin de la instrucción if
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                    + "el \n registro, no se encuentra una librería", 
                    "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                    + "hacer referencia \n de una instancia", 
                    "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                  + "intentar utilizar \n la librería o instancia para guardar", 
                  "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                  + "el manejo de la solicitud \n al intentar registrar datos "
                  + "\n" + ex.getMessage(), 
                  "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
        }//Fin de instrucción catch
    }//GEN-LAST:event_jTbtnGrabarActionPerformed

    private void jTbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbtnBuscarActionPerformed
        try {
            // Realizar el filtrado de un registro indicado por inns:            
            int val = Integer.parseInt(this.jTxtInss.getText()); 
            PersonalOperativo p = CtrlOperativo.leerRegistro(val);
            //Si se obtuvo el registro, se muestra
            if (p != null) {
                this.jTxtNombres.setText(p.getNombres());
                this.jTxtPApellido.setText(p.getpApellido());
                this.jTxtSApellido.setText(p.getsApellido());
                this.jTxtCorreo.setText(p.getCorreo());
                this.jCmbFuncion.setSelectedItem(p.getCargo());
            }//Fin de la instrucción if
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                    + "el \n registro, no se encuentra una librería", 
                    "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
           JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                    + "hacer referencia \n de una instancia", 
                    "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE); 
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                  + "intentar utilizar \n la librería o instancia para guardar", 
                  "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                  + "el manejo de la solicitud \n en recurso de Base de Datos"
                  + ex.getMessage(), 
                  "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jTbtnBuscarActionPerformed

    private void jTbtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbtnBajaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int opc; //Determina el boton seleccionado en el mensaje de confirmación        
        try {
            opc = JOptionPane.showConfirmDialog(this, "Esta intentando eliminar"
                                            + " un registro que contiene más \n"
                                            + " vinculaciones con otros datos"
                                            + " ¿Esta seguro de continuar?" ,                    
                                      "Eliminar", JOptionPane.YES_NO_OPTION, 
                                      JOptionPane.WARNING_MESSAGE);
            if (opc == JOptionPane.YES_OPTION)
                CtrlOperativo.eliminar(Integer.parseInt(this.jTxtInss.getText()));
                JOptionPane.showMessageDialog(this, "El registro del Empleado:"
                                             + this.jTxtInss.getText() + 
                                             "\n ha sido removido", "Eliminar",
                                             JOptionPane.INFORMATION_MESSAGE);
                this.clearForm();
        }
        catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                    + "el \n registro, no se encuentra una librería", 
                    "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                    + "hacer referencia \n de una instancia", 
                    "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                  + "intentar utilizar \n la librería o instancia para guardar", 
                  "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                  + "el manejo de la solicitud \n al intentar registrar datos "
                  + ex.getMessage(), 
                  "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
        }//Fin de instrucción catch 
               
    }//GEN-LAST:event_jTbtnBajaActionPerformed

    private void jTbtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbtnListarActionPerformed
        // TODO add your handling code here:
        Jif_ListaPersonalOperativo listP = new Jif_ListaPersonalOperativo ();
        this.getParent().add(listP);
        listP.show();
    }//GEN-LAST:event_jTbtnListarActionPerformed

    private void clearForm () {
        this.jTxtInss.setText("");
        this.jTxtNombres.setText("");
        this.jTxtPApellido.setText("");
        this.jTxtSApellido.setText("");
        this.jTxtCorreo.setText("");
        this.jCmbFuncion.setSelectedIndex(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCmbFuncion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblApellido1;
    private javax.swing.JLabel jLblCorreo;
    private javax.swing.JLabel jLblNombres;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JLabel jLbl_INSS;
    private javax.swing.JLabel jLbl_Image;
    private javax.swing.JPanel jPnlNav;
    private javax.swing.JToggleButton jTbtnBaja;
    private javax.swing.JToggleButton jTbtnBuscar;
    private javax.swing.JToggleButton jTbtnGrabar;
    private javax.swing.JToggleButton jTbtnListar;
    private javax.swing.JTextField jTxtCorreo;
    private javax.swing.JTextField jTxtInss;
    private javax.swing.JTextField jTxtNombres;
    private javax.swing.JTextField jTxtPApellido;
    private javax.swing.JTextField jTxtSApellido;
    // End of variables declaration//GEN-END:variables
}
