/*
 * Proyecto: Sistema para el control de Registro y Solicitudes de Titulos
 * Descripción: Esta clase representa un instancia en el nivel intermedio de la
 *              aplicación, toma los datos de vista del usuario y comunica hacia
 *              la capa de negocio para el procesamiento de la información por 
 *              de una instancia de Personal Operativo
 * Fecha: 18/05/2023
 */
package ui;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ui.operation.FrmActasDefensa;

/**
 *
 * @author lnarvaezb
 */
public class Sistema_UI extends javax.swing.JFrame {

    /**
     * Creates new form Sistema_UI
     */
    public Sistema_UI() {        
        initComponents();
        //Maximizar la ventana de inicio        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        dskPanel = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jItemPersonal = new javax.swing.JMenu();
        jItem_Estudiante = new javax.swing.JMenuItem();
        jItemPerOperativo = new javax.swing.JMenuItem();
        jItem_Tutor = new javax.swing.JMenuItem();
        jItem_Evaluador = new javax.swing.JMenuItem();
        jmnu_Transacciones = new javax.swing.JMenu();
        itemActDefensa = new javax.swing.JMenuItem();
        itemTramTitulo = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        jmnu_Reportes = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jmnu_Configuracion = new javax.swing.JMenu();
        jItem_Usuario = new javax.swing.JMenuItem();
        jSep_BaseDatos = new javax.swing.JPopupMenu.Separator();
        jItem_ConfDB = new javax.swing.JMenuItem();
        jMnu_Sesion = new javax.swing.JMenu();
        jItem_Sesion = new javax.swing.JMenuItem();
        jItem_Exit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Registros Academico Estudiantil");

        jItemPersonal.setMnemonic('f');
        jItemPersonal.setText("Catálogo");

        jItem_Estudiante.setMnemonic('o');
        jItem_Estudiante.setText("Estudiante");
        jItem_Estudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jItemPersonal.add(jItem_Estudiante);

        jItemPerOperativo.setMnemonic('s');
        jItemPerOperativo.setText("Personal Operativo");
        jItemPerOperativo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jItemPerOperativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemPerOperativoActionPerformed(evt);
            }
        });
        jItemPersonal.add(jItemPerOperativo);

        jItem_Tutor.setMnemonic('a');
        jItem_Tutor.setText("Tutor");
        jItem_Tutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jItemPersonal.add(jItem_Tutor);

        jItem_Evaluador.setMnemonic('x');
        jItem_Evaluador.setText("Evaludor");
        jItem_Evaluador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jItem_Evaluador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItem_EvaluadorActionPerformed(evt);
            }
        });
        jItemPersonal.add(jItem_Evaluador);

        menuBar.add(jItemPersonal);

        jmnu_Transacciones.setMnemonic('e');
        jmnu_Transacciones.setText("Solicitud");

        itemActDefensa.setMnemonic('t');
        itemActDefensa.setText("Acta de Defensa");
        itemActDefensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActDefensaActionPerformed(evt);
            }
        });
        jmnu_Transacciones.add(itemActDefensa);

        itemTramTitulo.setMnemonic('y');
        itemTramTitulo.setText("Tramite de Titulo");
        jmnu_Transacciones.add(itemTramTitulo);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        jmnu_Transacciones.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        jmnu_Transacciones.add(deleteMenuItem);

        menuBar.add(jmnu_Transacciones);

        jmnu_Reportes.setMnemonic('h');
        jmnu_Reportes.setText("Reportes");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Carta Egresado");
        jmnu_Reportes.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Asignaturas Aprobadas");
        jmnu_Reportes.add(aboutMenuItem);

        menuBar.add(jmnu_Reportes);

        jmnu_Configuracion.setText("Configuración");

        jItem_Usuario.setText("Cuenta Usuario");
        jItem_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jItem_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItem_UsuarioActionPerformed(evt);
            }
        });
        jmnu_Configuracion.add(jItem_Usuario);
        jmnu_Configuracion.add(jSep_BaseDatos);

        jItem_ConfDB.setText("Configurar Base de Datos");
        jItem_ConfDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jItem_ConfDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItem_ConfDBActionPerformed(evt);
            }
        });
        jmnu_Configuracion.add(jItem_ConfDB);

        menuBar.add(jmnu_Configuracion);

        jMnu_Sesion.setText("Sesión");
        jMnu_Sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jItem_Sesion.setText("Cerrar Sesión");
        jItem_Sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMnu_Sesion.add(jItem_Sesion);

        jItem_Exit.setText("Cerrar Sistema");
        jItem_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItem_ExitActionPerformed(evt);
            }
        });
        jMnu_Sesion.add(jItem_Exit);

        menuBar.add(jMnu_Sesion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jItem_EvaluadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItem_EvaluadorActionPerformed
       
    }//GEN-LAST:event_jItem_EvaluadorActionPerformed

    private void jItem_ConfDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItem_ConfDBActionPerformed
        // TODO add your handling code here:
        Conf_Server config = new Conf_Server ();
        this.dskPanel.add(config);
        config.show();
    }//GEN-LAST:event_jItem_ConfDBActionPerformed

    private void jItem_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItem_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jItem_UsuarioActionPerformed

    private void jItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItem_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jItem_ExitActionPerformed

    private void jItemPerOperativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemPerOperativoActionPerformed
        // TODO add your handling code here:
        FrmPersonalOperativo tecnico;
        tecnico = new FrmPersonalOperativo (); //Crear la instancia
        this.dskPanel.add(tecnico); //Agregar al Panel
        tecnico.show(); //Mostrar el formulario
    }//GEN-LAST:event_jItemPerOperativoActionPerformed

    private void itemActDefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActDefensaActionPerformed
        // TODO add your handling code here:
        FrmActasDefensa frmActa = new FrmActasDefensa ();
        this.dskPanel.add(frmActa); //Agregar al escritorio
        frmActa.show();
    }//GEN-LAST:event_itemActDefensaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema_UI().setVisible(true);
            }
        });
    //Preparar la carga de archivos de configuración
        try {
        
            FileInputStream fis = new FileInputStream (System.getProperty(
                                   "user.dir") + "\\src\\servicios\\config.txt");
            Properties p = new Properties (System.getProperties());
            p.load(fis);
            System.setProperties(p);
        }
        catch (java.io.FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Archivo de Configuración"
                + " de acceso a datos \n no encontrado, revisar configuración",
                "Configuración de acceso", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }//Fin de la instrucción catch
        
        catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error en lectura de datos "
                                        + "de inicio de configuración   \n",
                                         "Error al leer configuración", 
                                         JOptionPane.ERROR_MESSAGE);
            System.exit(0);
    }//Fin catch)
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane dskPanel;
    private javax.swing.JMenuItem itemActDefensa;
    private javax.swing.JMenuItem itemTramTitulo;
    private javax.swing.JMenuItem jItemPerOperativo;
    private javax.swing.JMenu jItemPersonal;
    private javax.swing.JMenuItem jItem_ConfDB;
    private javax.swing.JMenuItem jItem_Estudiante;
    private javax.swing.JMenuItem jItem_Evaluador;
    private javax.swing.JMenuItem jItem_Exit;
    private javax.swing.JMenuItem jItem_Sesion;
    private javax.swing.JMenuItem jItem_Tutor;
    private javax.swing.JMenuItem jItem_Usuario;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMnu_Sesion;
    private javax.swing.JPopupMenu.Separator jSep_BaseDatos;
    private javax.swing.JMenu jmnu_Configuracion;
    private javax.swing.JMenu jmnu_Reportes;
    private javax.swing.JMenu jmnu_Transacciones;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
