/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui.operation;

import controlador.CtrlActas;
import controlador.CtrlDepartamento;
import controlador.CtrlFacultad;
import controlador.CtrlTutores;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author lnarvaezb
 */
public class FrmActasDefensa extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmActasDefensa
     */
    public FrmActasDefensa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollMain = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLblTitulo = new javax.swing.JLabel();
        jTabActas = new javax.swing.JTabbedPane();
        jPnlActa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtNumActa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDpckFecha = new org.jdatepicker.JDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jCmbFacultad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jCmbDepartamento = new javax.swing.JComboBox<>();
        jCmbModalidad = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtLocacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrTextArea = new javax.swing.JScrollPane();
        jTxtTitulo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTxtTutor = new javax.swing.JTextField();
        jBtnTutor = new javax.swing.JButton();
        jPnlDetalle = new javax.swing.JPanel();
        jPnlEvaluador = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTxtEvaluador1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtEvaluador2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtEvaluador3 = new javax.swing.JTextField();
        jChkPresidente = new javax.swing.JCheckBox();
        jChkSecretario = new javax.swing.JCheckBox();
        jChkVocal = new javax.swing.JCheckBox();
        jBtnEval1 = new javax.swing.JButton();
        jBtnEval2 = new javax.swing.JButton();
        jBtnEval3 = new javax.swing.JButton();
        jPnlBachiller = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTxtEstudiante1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtEstudiante2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtEstudiante3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTxtCarne1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTxtCarne2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTxtCarne3 = new javax.swing.JTextField();
        jPnlGuardar = new javax.swing.JPanel();
        jTbtnGuardar = new javax.swing.JToggleButton();

        jScrollMain.setViewportView(jEditorPane1);

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblTitulo.setText("Acta de Defensa de Modalidad de Graduación");

        jPnlActa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPnlActa.setPreferredSize(new java.awt.Dimension(860, 360));

        jLabel2.setText("N° de Acta");

        jTxtNumActa.setEditable(false);
        jTxtNumActa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Fecha");

        jDpckFecha.setToolTipText("Fecha de Defensa");
        jDpckFecha.setPreferredSize(new java.awt.Dimension(200, 24));

        jLabel4.setText("Facultad");

        jCmbFacultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        jCmbFacultad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setText("Departamento");

        jCmbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        jCmbDepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCmbModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "MONOGRAFIA", "SEMINARIO DE GRADUACION" }));
        jCmbModalidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setText("Modalidad");

        jLabel6.setText("Local");

        jLabel14.setText("Titulo del Trabajo");

        jTxtTitulo.setColumns(20);
        jTxtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtTitulo.setRows(5);
        jScrTextArea.setViewportView(jTxtTitulo);

        jLabel1.setText("Tutor");

        jBtnTutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn_lupa_busc32.png"))); // NOI18N
        jBtnTutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlActaLayout = new javax.swing.GroupLayout(jPnlActa);
        jPnlActa.setLayout(jPnlActaLayout);
        jPnlActaLayout.setHorizontalGroup(
            jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlActaLayout.createSequentialGroup()
                .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnlActaLayout.createSequentialGroup()
                        .addContainerGap(54, Short.MAX_VALUE)
                        .addComponent(jScrTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlActaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlActaLayout.createSequentialGroup()
                                .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPnlActaLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(339, 339, 339))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlActaLayout.createSequentialGroup()
                                        .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPnlActaLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTxtTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPnlActaLayout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jCmbModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPnlActaLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTxtLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPnlActaLayout.createSequentialGroup()
                                        .addComponent(jBtnTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlActaLayout.createSequentialGroup()
                                .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCmbFacultad, 0, 338, Short.MAX_VALUE)
                                    .addComponent(jTxtNumActa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlActaLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlActaLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDpckFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(30, 30, 30))
        );
        jPnlActaLayout.setVerticalGroup(
            jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlActaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlActaLayout.createSequentialGroup()
                        .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jDpckFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPnlActaLayout.createSequentialGroup()
                        .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNumActa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(16, 16, 16)
                        .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCmbFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(16, 16, 16)
                .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCmbModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6))
                    .addComponent(jTxtLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlActaLayout.createSequentialGroup()
                        .addGroup(jPnlActaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlActaLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1))
                            .addComponent(jTxtTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel14))
                    .addComponent(jBtnTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabActas.addTab("Datos Geneales Acta", jPnlActa);

        jPnlDetalle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jPnlEvaluador.setBorder(javax.swing.BorderFactory.createTitledBorder("Comite Evaluador"));
        jPnlEvaluador.setPreferredSize(new java.awt.Dimension(710, 150));

        jLabel8.setText("Evaluador 1");

        jTxtEvaluador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEvaluador1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Evaluador 2");

        jLabel10.setText("Evaludaro 3");

        jChkPresidente.setText("Presidente");

        jChkSecretario.setText("Secretario");

        jChkVocal.setText("Vocal");

        jBtnEval1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn_lupa_busc32.png"))); // NOI18N
        jBtnEval1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jBtnEval2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn_lupa_busc32.png"))); // NOI18N
        jBtnEval2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jBtnEval3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn_lupa_busc32.png"))); // NOI18N
        jBtnEval3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnEval3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPnlEvaluadorLayout = new javax.swing.GroupLayout(jPnlEvaluador);
        jPnlEvaluador.setLayout(jPnlEvaluadorLayout);
        jPnlEvaluadorLayout.setHorizontalGroup(
            jPnlEvaluadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEvaluadorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPnlEvaluadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlEvaluadorLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtEvaluador1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnEval1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlEvaluadorLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtEvaluador2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnEval2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlEvaluadorLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtEvaluador3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnEval3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlEvaluadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChkSecretario)
                    .addComponent(jChkPresidente)
                    .addComponent(jChkVocal))
                .addGap(22, 22, 22))
        );
        jPnlEvaluadorLayout.setVerticalGroup(
            jPnlEvaluadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEvaluadorLayout.createSequentialGroup()
                .addGroup(jPnlEvaluadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlEvaluadorLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPnlEvaluadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtEvaluador1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPnlEvaluadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jChkPresidente)
                        .addComponent(jBtnEval1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPnlEvaluadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlEvaluadorLayout.createSequentialGroup()
                        .addGroup(jPnlEvaluadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlEvaluadorLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel9))
                            .addGroup(jPnlEvaluadorLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jChkSecretario)))
                        .addGap(18, 18, 18)
                        .addComponent(jChkVocal))
                    .addGroup(jPnlEvaluadorLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jBtnEval2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnEval3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlEvaluadorLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTxtEvaluador2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPnlEvaluadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtEvaluador3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPnlBachiller.setBorder(javax.swing.BorderFactory.createTitledBorder("Bachilleres"));

        jLabel11.setText("Evaluado 1");

        jLabel12.setText("Evaluado 2");

        jLabel13.setText("Evaluado 3");

        jLabel15.setText("Carné");

        jLabel16.setText("Carné");

        jLabel17.setText("Carné");

        javax.swing.GroupLayout jPnlBachillerLayout = new javax.swing.GroupLayout(jPnlBachiller);
        jPnlBachiller.setLayout(jPnlBachillerLayout);
        jPnlBachillerLayout.setHorizontalGroup(
            jPnlBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBachillerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPnlBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlBachillerLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtEstudiante3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlBachillerLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtEstudiante2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlBachillerLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPnlBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPnlBachillerLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCarne3))
                    .addGroup(jPnlBachillerLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCarne2))
                    .addGroup(jPnlBachillerLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCarne1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        jPnlBachillerLayout.setVerticalGroup(
            jPnlBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBachillerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPnlBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnlBachillerLayout.createSequentialGroup()
                        .addGroup(jPnlBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTxtCarne1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnlBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTxtCarne2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnlBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTxtCarne3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnlBachillerLayout.createSequentialGroup()
                        .addGroup(jPnlBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTxtEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnlBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTxtEstudiante2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnlBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTxtEstudiante3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnlDetalleLayout = new javax.swing.GroupLayout(jPnlDetalle);
        jPnlDetalle.setLayout(jPnlDetalleLayout);
        jPnlDetalleLayout.setHorizontalGroup(
            jPnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDetalleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPnlEvaluador, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addComponent(jPnlBachiller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPnlDetalleLayout.setVerticalGroup(
            jPnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDetalleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPnlEvaluador, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnlBachiller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabActas.addTab("Detalles Acta", jPnlDetalle);

        jPnlGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/guardar_24.gif"))); // NOI18N
        jTbtnGuardar.setText("Guardar");
        jTbtnGuardar.setToolTipText("Aplicar Guardado de los cambios");
        jTbtnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTbtnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jTbtnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jTbtnGuardar.setIconTextGap(2);
        jTbtnGuardar.setMargin(new java.awt.Insets(2, 4, 2, 4));

        javax.swing.GroupLayout jPnlGuardarLayout = new javax.swing.GroupLayout(jPnlGuardar);
        jPnlGuardar.setLayout(jPnlGuardarLayout);
        jPnlGuardarLayout.setHorizontalGroup(
            jPnlGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTbtnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlGuardarLayout.setVerticalGroup(
            jPnlGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTbtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabActas)
                    .addComponent(jPnlGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblTitulo)
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPnlGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jTabActas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabActas.getAccessibleContext().setAccessibleName("jtab_general");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtEvaluador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEvaluador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEvaluador1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // Establecer código automatico del número de acta
                
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // Generar el código del acta        
        int num = CtrlActas.generarNumActa();        
        this.jTxtNumActa.setText(Integer.toString(num));
        
        //Cargar el combo de Facultades y Departamentos        
        try {
            //1. Cargar la lista de Facultades
            for (String name : CtrlFacultad.listar()){
                this.jCmbFacultad.addItem(name);
            }//Fin de for
            
            //2. Cargar la lista de departamentos
            for (String dpto : CtrlDepartamento.listar()){
                this.jCmbDepartamento.addItem(dpto);
            }//Fin for departamentos            
        }
        catch (ClassNotFoundException | InstantiationException | 
                     IllegalAccessException | SQLException ex){
                JOptionPane.showMessageDialog(null, "Se ha provocado una falla"
                        + "al tratar de listar Facultades y Departamentos \n "
                        + " registrados actualmente", "Error al cargar"
                                + "listado",JOptionPane.ERROR_MESSAGE);
        }//Fin instrucción catch
    }//GEN-LAST:event_formInternalFrameActivated

    private void jBtnTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTutorActionPerformed
        // TODO add your handling code here:
        String email = JOptionPane.showInputDialog(this, "Digitel "
                + "correo electrónico del tutor",
                  "Tutor a Buscar", JOptionPane.INFORMATION_MESSAGE);
        //Buscar el Tutor de acuerdo al corre electrónco especificado
        try {
               this.jTxtTutor.setText(CtrlTutores.buscarTutor(email));
            }
        catch (ClassNotFoundException | InstantiationException | 
                     IllegalAccessException | SQLException ex){
                JOptionPane.showMessageDialog(null, "No se ha podido"
                        + " identificar al tutor \n " + ex.getMessage()
                        + " indicado por dirección de correo", 
                        "Registro no encontrado"
                        + "listado",JOptionPane.ERROR_MESSAGE);
        }//Fin de la instrucciones catch
    }//GEN-LAST:event_jBtnTutorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEval1;
    private javax.swing.JButton jBtnEval2;
    private javax.swing.JButton jBtnEval3;
    private javax.swing.JButton jBtnTutor;
    private javax.swing.JCheckBox jChkPresidente;
    private javax.swing.JCheckBox jChkSecretario;
    private javax.swing.JCheckBox jChkVocal;
    private javax.swing.JComboBox<String> jCmbDepartamento;
    private javax.swing.JComboBox<String> jCmbFacultad;
    private javax.swing.JComboBox<String> jCmbModalidad;
    private org.jdatepicker.JDatePicker jDpckFecha;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JPanel jPnlActa;
    private javax.swing.JPanel jPnlBachiller;
    private javax.swing.JPanel jPnlDetalle;
    private javax.swing.JPanel jPnlEvaluador;
    private javax.swing.JPanel jPnlGuardar;
    private javax.swing.JScrollPane jScrTextArea;
    private javax.swing.JScrollPane jScrollMain;
    private javax.swing.JTabbedPane jTabActas;
    private javax.swing.JToggleButton jTbtnGuardar;
    private javax.swing.JTextField jTxtCarne1;
    private javax.swing.JTextField jTxtCarne2;
    private javax.swing.JTextField jTxtCarne3;
    private javax.swing.JTextField jTxtEstudiante1;
    private javax.swing.JTextField jTxtEstudiante2;
    private javax.swing.JTextField jTxtEstudiante3;
    private javax.swing.JTextField jTxtEvaluador1;
    private javax.swing.JTextField jTxtEvaluador2;
    private javax.swing.JTextField jTxtEvaluador3;
    private javax.swing.JTextField jTxtLocacion;
    private javax.swing.JTextField jTxtNumActa;
    private javax.swing.JTextArea jTxtTitulo;
    private javax.swing.JTextField jTxtTutor;
    // End of variables declaration//GEN-END:variables
}
